/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthTopBar: typeof import('./../../components/core/views/login/AuthTopBar.vue')['default']
    CheckpointTable: typeof import('./../../components/business/task-dispatch/modules/task-monitoring/checkpoint-table.vue')['default']
    CommentItem: typeof import('./../../components/business/comment-widget/widget/CommentItem.vue')['default']
    CommentWidget: typeof import('./../../components/business/comment-widget/index.vue')['default']
    ConfigSnapshot: typeof import('./../../components/business/task-dispatch/modules/task-monitoring/config-snapshot.vue')['default']
    ExecutionPanel: typeof import('./../../components/business/execution-panel.vue')['default']
    LfpBarChart: typeof import('./../../components/core/charts/lfp-bar-chart/index.vue')['default']
    LfpBarChartCard: typeof import('./../../components/core/cards/lfp-bar-chart-card/index.vue')['default']
    LfpBreadcrumb: typeof import('./../../components/core/layouts/lfp-breadcrumb/index.vue')['default']
    LfpButtonTable: typeof import('./../../components/core/forms/lfp-button-table/index.vue')['default']
    LfpCountTo: typeof import('./../../components/core/text-effect/lfp-count-to/index.vue')['default']
    LfpDataListCard: typeof import('./../../components/core/cards/lfp-data-list-card/index.vue')['default']
    LfpDonutChartCard: typeof import('./../../components/core/cards/lfp-donut-chart-card/index.vue')['default']
    LfpException: typeof import('./../../components/core/views/exception/LfpException.vue')['default']
    LfpFestivalTextScroll: typeof import('./../../components/core/text-effect/lfp-festival-text-scroll/index.vue')['default']
    LfpGlobalComponent: typeof import('./../../components/core/layouts/lfp-global-component/index.vue')['default']
    LfpGlobalSearch: typeof import('./../../components/core/layouts/lfp-global-search/index.vue')['default']
    LfpHeaderBar: typeof import('./../../components/core/layouts/lfp-header-bar/index.vue')['default']
    LfpIconButton: typeof import('./../../components/core/widget/lfp-icon-button/index.vue')['default']
    LfpLineChartCard: typeof import('./../../components/core/cards/lfp-line-chart-card/index.vue')['default']
    LfpLogo: typeof import('./../../components/core/base/lfp-logo/index.vue')['default']
    LfpPageContent: typeof import('./../../components/core/layouts/lfp-page-content/index.vue')['default']
    LfpSidebarMenu: typeof import('./../../components/core/layouts/lfp-sidebar-menu/index.vue')['default']
    LfpStatsCard: typeof import('./../../components/core/cards/lfp-stats-card/index.vue')['default']
    LfpSvgIcon: typeof import('./../../components/core/base/lfp-svg-icon/index.vue')['default']
    LfpTable: typeof import('./../../components/core/tables/lfp-table/index.vue')['default']
    LfpTaskListCard: typeof import('./../../components/core/cards/lfp-task-list-card/index.vue')['default']
    LfpTimelineListCard: typeof import('./../../components/core/cards/lfp-timeline-list-card/index.vue')['default']
    LfpUserMenu: typeof import('./../../components/core/layouts/lfp-header-bar/widget/LfpUserMenu.vue')['default']
    LoginLeftView: typeof import('./../../components/core/views/login/LoginLeftView.vue')['default']
    LossChart: typeof import('./../../components/business/task-dispatch/modules/task-monitoring/loss-chart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskConsole: typeof import('./../../components/business/task-dispatch/modules/task-console.vue')['default']
    TaskDashboard: typeof import('./../../components/business/task-dispatch/modules/task-dashboard.vue')['default']
    Terminal: typeof import('./../../components/business/task-dispatch/modules/task-monitoring/terminal.vue')['default']
    ThemeSvg: typeof import('./../../components/core/theme/theme-svg/index.vue')['default']
  }
}
